<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\StockIn;
use App\Models\Category;
use App\Models\Pricing;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StockInController extends Controller
{
    public function index()
    {
        $existingProducts = Product::where('ProductStatus', 'Active')
            ->with(['category', 'supplier', 'pricing' => function($query) {
                $query->where('IsActive', 'yes')->latest('EffectiveDate');
            }])
            ->get();
        
        $categories = Category::all();
        
        $stockIns = StockIn::with(['product.category', 'product.supplier', 'product.pricing' => function($query) {
                $query->where('IsActive', 'yes')->latest('EffectiveDate');
            }])
            ->orderBy('DateRcvd', 'desc')
            ->orderBy('created_at', 'desc')
            ->get();
        
        return view('admin.stockin', compact(
            'existingProducts', 
            'categories', 
            'stockIns'
        ));
    }
    
    public function store(Request $request)
    {
        $request->validate([
            'ProductID' => 'required|exists:products,ProductID',
            'Qty' => 'required|integer|min:1',
            'ProdStatus' => 'required|in:Received,Defective,Expired',
            'DateRcvd' => 'required|date',
            'OriginalPrice' => 'required|numeric|min:0',
            'MarkupRate' => 'required|numeric|min:0',
            'RetailPrice' => 'required|numeric|min:0',
            'ReorderLevel' => 'nullable|integer|min:1',
        ]);

        DB::transaction(function () use ($request) {
            // Create Stock In Record (StockInID is auto-generated by model)
            $stockIn = StockIn::create([
                'ProductID' => $request->ProductID,
                'SupplierID' => $request->SupplierID,
                'Qty' => $request->Qty,
                'ProdStatus' => $request->ProdStatus,
                'DateRcvd' => $request->DateRcvd,
                'ExpirationDate' => $request->ExpirationDate ?? null,
            ]);

            // Update Product Stock Qty and Reorder Level
            $product = Product::find($request->ProductID);
            
            if ($request->ProdStatus == 'Received') {
                $product->StockQty += $request->Qty;
            }
            
            // Update reorder level if provided
            if ($request->has('ReorderLevel') && $request->ReorderLevel > 0) {
                $product->ReorderLevel = $request->ReorderLevel;
            }
            
            $product->save();

            // Update or Create Pricing
            // First, deactivate old pricing records for this product
            Pricing::where('ProductID', $product->ProductID)
                ->where('IsActive', 'yes')
                ->update(['IsActive' => 'no']);
            
            // Create new pricing record with auto-generated ID
            Pricing::create([
                'ProductID' => $product->ProductID,
                'OriginalPrice' => $request->OriginalPrice,
                'MarkupRate' => $request->MarkupRate,
                'RetailPrice' => $request->RetailPrice,
                'EffectiveDate' => now(),
                'IsActive' => 'yes'
            ]);
        });

        return redirect()->route('admin.stockin')->with('success', 'Stock added successfully!');
    }
    
    public function getProductPricing($id)
    {
        $product = Product::with(['pricing' => function($query) {
            $query->where('IsActive', 'yes')->latest('EffectiveDate')->first();
        }])->findOrFail($id);
        
        return response()->json([
            'success' => true,
            'originalPrice' => $product->pricing->OriginalPrice ?? null,
            'markupRate' => $product->pricing->MarkupRate ?? null,
            'retailPrice' => $product->pricing->RetailPrice ?? null,
        ]);
    }
    
    public function show($id)
    {
        try {
            $stock = StockIn::with([
                'product.category', 
                'product.supplier', 
                'product.pricing' => function($query) {
                    $query->where('IsActive', 'yes')->latest('EffectiveDate')->first();
                },
                'supplier'
            ])
            ->findOrFail($id);
            
            return response()->json([
                'success' => true,
                'stock_in' => $stock,
                'product' => $stock->product,
                'pricing' => $stock->product->pricing ?? null,
                'supplier' => $stock->supplier ?? $stock->product->supplier ?? null,
                'category' => $stock->product->category ?? null
            ]);
            
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'error' => 'Stock record not found',
                'message' => $e->getMessage()
            ], 404);
        }
    }
}